server:
  port: 7101

eureka:
  instance:
    hostname: product1
    prefer-ip-address: true

spring:
  application:
    name: product
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///microService?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: 123456
  redis:
    host: localhost
    port: 6379
    timeout: 1000
    jedis:
      pool:
        min-idle: 5
        max-active: 10
        max-idle: 10
        max-wait: 2000

mybatis:
  mapper-locations: classpath:mapper/*.xml
