server:
  port: 7101

eureka:
  instance:
    hostname: product1
    prefer-ip-address: true

spring:
  application:
    name: product
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///microService?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: 123456
  redis:
    host: localhost
    port: 6379
    timeout: 1000
    jedis:
      pool:
        min-idle: 5
        max-active: 10
        max-idle: 10
        max-wait: 2000

mybatis:
  mapper-locations: classpath:mapper/*.xml

hystrix:
  command:
    default:
      circuitBreaker:
        errorThresholdPercentage: 50
        requestVolumeThreshold: 10
        sleepWindowInMilliseconds: 20000
      metrics:
        rollingStats:
          timeInMilliseconds: 20000
management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  rabbitmq:
    addresses: 49.234.95.144:5672
    connection-timeout: 10000
    password: guest
    publisher-confirm-type: simple
    publisher-returns: true
    template:
      mandatory: true
    username: guest
    virtual-host: /
